### PR TITLE
Shows selected comic from the command line

### PR DESCRIPTION
**Pull request by BlitzKraft**
Requires feh. WIP on a more universal solution using `xdg-open`.

### CODE REVIEW

**Comment by prodicus** [comment]
Hey @BlitzKraft . Cool. Could you show me gif of it working? Would love to see it in action :smile: 
And do edit the README to include this feature along with the gif

Cheers!

**Comment by BlitzKraft** [comment]
Here's some screencast:
xkcd out
xkcd2 out

The gifs are not the best. I will have something better for the readme.

**Comment by prodicus** [comment]
Good job @BlitzKraft :+1: 

You can have a look at SimpleScreenRecorder, gets the job done for me. 

Have you tested this subprocess call on other systems?

**Comment by prodicus** [comment]
By the way. Your prompt looks slick! What are you using?

**Comment by BlitzKraft** [comment]
SimpleScreenRecorder is what I used. That was the first google result. I thought subprocess was a python native library. I only have my own computer to test it with. 

Here's python docs for [subprocess](https://docs.python.org/3/library/subprocess.html). 

The prompt is [powerline](https://github.com/powerline/powerline).

**Comment by prodicus** [comment]
Dumb question. Sorry. It will work. 

Man I couldn't get powerline to work on my Ubuntu. -_-

Not sure whats the issue

**Comment by BlitzKraft** [comment]
It came a long way. It was not easy the first time I tried it. Almost moved to zsh, just to get the git branch to show up. I really love that feature. 

Now it almost* just works. A lot fewer issues. [Powerline + tmux = bliss](http://imgur.com/XFwPGv2)

**Comment by BlitzKraft** [comment]
@prodicus Question: Is there a way to remember the users' choice for an option?
I want the image viewer to be user selectable. Especially in cases where there is no xserver running; user may specify, a persistent option/flag for the default image handler command.

**Comment by prodicus** [comment]
Well you could open the latest xkcd uploaded when no option is given when opening the image. Well but that's just me. 

But we should not be making any assumptions when designing the interface for that. 

What do you suggest @BlitzKraft ?

**Comment by BlitzKraft** [comment]
xdg-open relies on xserver. If there is no x running, any common image viewer throws an error. I ran xdg-open on my system, without x; the command went through to eog, as expected, but eog failed. No x. 

However, `fbv` another image viewer, can render without using x. I am considering adding a variable, default image viewer command, which can be set by the user. If unset, defaults to using xdg-open as earlier.

**Comment by prodicus** [comment]
But a user not running xserver would be one of our rarest users. Not hating on the creativity, but this looks like an overkill to me @BlitzKraft !

**Comment by BlitzKraft** [comment]
I agree. That's probably overkill. Wanted to hear your thoughts on it. 

I am not a fan of xdg-open, but it works. So leaving it there, for now.

**Comment by prodicus** [comment]
@BlitzKraft :+1: 

Happy hacking :smile: !

**Pull request merged**
