### PR TITLE
Trim - WIP

### PR DESCRIPTION
**Pull request by BlitzKraft**
Don't merge yet. I need to remove docopts and see if bs4 can be done away with.

### CODE REVIEW

**Comment by BlitzKraft** [comment]
There are some major changes. I am considering a version bump to 0.1.0.

What do you think?

**Comment by prodicus** [comment]
Great job @BlitzKraft.

I still see an import of the `bs4` module. But aren't you now using the `JSON` data from their API? So no need to scrape I guess.

**Comment by BlitzKraft** [comment]
It's still being used for the dict update.

**Comment by prodicus** [comment]
@BlitzKraft Would it be possible to remove the bs4 dependency?

I think we can request the API for the 0th and the latest xkcd number and then in a loop update the dict. What do you think?

**Comment by BlitzKraft** [comment]
I will work on removing the bs4 dependency later this week. However I'll still be using the archive page instead of going in a loop.

**Comment by prodicus** [comment]
Can update the `requirements.txt` file?

Merging your PR after that. Looking forward to your next one :smile: @BlitzKraft

**Comment by BlitzKraft** [comment]
Done. And is wheel necessary too?

**Comment by prodicus** [comment]
Nope @BlitzKraft Merged it.

**Comment by BlitzKraft** [comment]
I haven't removed wheel, but there is one reference to it in `Makefile`.

```
Line 44:     python setup.py bdist_wheel
```

I haven't removed it this time, but include that in the next PR.

**Comment by prodicus** [comment]
Not an issue right now. I haven't updated this in the pypa. Next PR it is then

**Pull request merged**
