### PR TITLE
Exclude list

### PR DESCRIPTION
**Pull request by BlitzKraft**
An exclude list so that download all won't fail upon encountering the dynamic comics. The array needs to be manually updated though. 

Affects only the image download. Retrieves all the other metadata (description, link and alt text).

### CODE REVIEW

**Comment by prodicus** [comment]
I see that there are some merge conflicts. Could you update your branch with the master first?

**Comment by BlitzKraft** [comment]
I can't view the conflicts. This might be dumb, but how do I view conflicts on github?

**Comment by prodicus** [comment]
You have to first understand why merge conflicts occur in the first place. From what I have experienced so far is that they happen  when two people are working on the same source files. When they try to merge them, you get conflicts. I suggest googling a bit about it.

The thing is that we can't see them until they happen, so we should always work on the latest version of the package when working on a patch/feature per se.

In your case, I am guessing that you were working on the two features(the older PR and this one) simultaneously. So when I merged your previous PR, this PR was behind one commit from the master. And as you working on the same source files (modules if you may). I am getting merge conflicts when I try to merge your PR.

**Solution**

Update your branch `excludeList` with the master first and then try completing the feature.

Hope that helps :smile:

**Comment by BlitzKraft** [comment]
Crap. It took me a while to understand everything. 

I get it now. Thank you very much for the explanation. I am closing this pull request, delete the branch and complete the feature.

**Comment by prodicus** [comment]
@BlitzKraft Not a problem!

More than happy to help.

**Pull request closed without merging**
