### PR TITLE
Imageviewer can be specified by changing one variable

### PR DESCRIPTION
**Pull request by BlitzKraft**
IMAGE_HANDLER

### CODE REVIEW

**Comment by BlitzKraft** [comment]
@prodicus The package requires python3. The /usr/bin/env is set to python . Changed it too. 

If it is left at python (my default is at 2.7) it throws the error with version.

**Comment by prodicus** [comment]
@BlitzKraft Did you check it with both the versions of `python`?

**Comment by BlitzKraft** [comment]
Yes, I did. Python 2.7 threw an error and python3 didn't.

The original README says pip3, and not pip. I didn't know the difference then, but now I do.

**Comment by BlitzKraft** [comment]
A little more explanation to what I did:

 * Created a variable IMAGE_HANDLER which defaults to `xdg-open` by default, but can be changed to any value
 * Changed the quotations around strings to single quotes, except where the strings include a single quote.
* Users can change the value of this one variable to set a custom image viewer.

**Comment by prodicus** [comment]
:+1:

**Pull request merged**
