### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by BlitzKraft**
Left an old version of the file with the comments, for reference. Also serves as a reference for the future. But cli.py is clean and easy to follow.

### CODE REVIEW

**Comment by prodicus** [comment]
Good work @BlitzKraft :+1: 

I was thinking of removing the usage of the unwanted packages (`bs4`, `python magic`etc.) 

I will be merging this PR as you have put your time and hard work on it. But I really think for the next PR, instead of refactoring the existing codebase, we should start work with the API provided by xkcd. It's much less brittle!

What is your opinion on that?

**Comment by BlitzKraft** [comment]
I agree. But bs4 seems reasonable - grabbing the archive in one request, and parsing everything offline. And then using the json api for downloading the actual comics. 

I was looking for some native libraries that support html parsing, couldn't find any that handled it as concisely as bs4 does. Other than that, I would consider writing my own parsing method - but that's beyond me at the moment. 

As for magic, I guess reading the first few bytes of the binary file would suffice to distinguish between jpeg and png - that I can do and will be my next PR. 

Here are my targets, for the coming week:
Docopts, is easy to use, but not necessary - I think. Urllib.request can be done away with. 

What else do you have in mind?

**Comment by prodicus** [comment]
>grabbing the archive in one request, and parsing everything offline. And then using the json api for downloading the actual comics.

But wouldn't the JSON API just return JSON objects. So no need for an HTML parser (if I did understand what you were trying to convey)

Have a look at `mimetypes` in the standard library, I think it might give us the leverage to do away with `python magic`.

> Docopts, is easy to use, but not necessary

`argparse` would be the closest thing in the standard library which can replace it.

>`Urllib.request` can be done away with.

Are we not using `requests` for all that?

**Comment by BlitzKraft** [comment]
The archive is only being used to update the db. That seems to be the right choice. Because, json api returns only one comic. For updating, that would mean a ton of requests, just to update the db. XKCD's json does not provide an interface for downloading an archive. JSON requests are being used when there are download options given in the command line. 

I am looking into mimetypes. I agree, argparse is the way to go. 

There are still a few spots where urllib was used. I should change them to requests instead. 

My reason for the clean up was to make the code readable and the comments are breaking my flow. I almost expected you wouldn't be merging it. I am glad you did!

**Comment by prodicus** [comment]
Hey, you did some hard work on the previous PR. :smile: 

But I think the DB thingy is more of an anti feature. 

***

My thoughts 

[http://xkcd.com/info.0.json](http://xkcd.com/info.0.json)

returns 

```bash
{
	"month": "4",
	"num": 1665,
	"link": "",
	"year": "2016",
	"news": "",
	"safe_title": "City Talk Pages",
	"transcript": "",
	"alt": "I don't think the Lakeshore Air Crash Museum really belongs under 'Tourist Attractions.' It's not a museum--it's just an area near the Lake Festival Laser Show where a lot of planes have crashed.",
	"img": "http:\/\/imgs.xkcd.com\/comics\/city_talk_pages.png",
	"title": "City Talk Pages",
	"day": "8"
}
```

Now we have [http://xkcd.com/1/info.0.json](http://xkcd.com/1/info.0.json)

```bash
{
	"month": "1",
	"num": 1,
	"link": "",
	"year": "2006",
	"news": "",
	"safe_title": "Barrel - Part 1",
	"transcript": "[[A boy sits in a barrel which is floating in an ocean.]]\nBoy: I wonder where I'll float next?\n[[The barrel drifts into the distance. Nothing else can be seen.]]\n{{Alt: Don't we all.}}",
	"alt": "Don't we all.",
	"img": "http:\/\/imgs.xkcd.com\/comics\/barrel_cropped_(1).jpg",
	"title": "Barrel - Part 1",
	"day": "1"
}
```

Now we can run a loop when running `--dowload-all`

**Comment by BlitzKraft** [comment]
I agree we can run it and that it works. But compare that to having just one request get ALL the data required to populate the db, as opposed to making 1664 (currently) requests - for the information we don't use in the db at all. 

For the update db, all the data we need, is just the comic number. The dict is nice that it grabs the title and the published date, for a quick reference.

**Comment by prodicus** [comment]
Sounds good to me. I will leave that decision to you on how you go about it. :+1:

**Comment by BlitzKraft** [comment]
Great! I've got my weekend planned out for this. 

Now back to work!!

**Pull request merged**
