### PR TITLE
Download continues, if the comic is listed in the exclude list.

### PR DESCRIPTION
**Pull request by BlitzKraft**
Some xkcd comics don't have an image and the`--download-all` stops with an error causing the user(me) to run the same more than one time to get all the comics. 

With this, there is an option to exclude them from asking for an image and just get the listed info on the comic.

### CODE REVIEW

**Comment by prodicus** [comment]
Merging it.

**Comment by BlitzKraft** [comment]
Yes please.

**Comment by prodicus** [comment]
If you are on it then please consider this issue #10

**Comment by BlitzKraft** [comment]
Yes, I was going through the list of issues. I will be cleaning up as much as I can.

**Pull request merged**
