### PR TITLE
Adding custom --path=PATH

### PR DESCRIPTION
**Pull request by lethargilistic**
This does not create any directories if the path does not exist, but that could be a potential feature as a different option. For my own comic archiver, I used a --pathc=PATH for that.

### CODE REVIEW

**Comment by prodicus** [comment]
Awesome work @lethargilistic :smile:

**Comment by lethargilistic** [comment]
Of course, @prodicus. :smile_cat:

**Comment by prodicus** [comment]
So what are you working on now @lethargilistic ?

**Comment by lethargilistic** [comment]
@prodicusTrying to find a programming job is the priority, but I'm editing the documentation of a web framework called [weppy](https://github.com/gi0baro/weppy). I found it much more usable than Django. :laughing:

**Pull request merged**
